name: Deploy to Google Cloud Run with Manual Approval and Rollback

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      actions: 'write'  # Requerido para approvals y environments

    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
      url: https://console.cloud.google.com/run

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set Cloud Run Service Name
        id: service-name
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "SERVICE_NAME=calculadora-fertilidad-app" >> $GITHUB_ENV
          else
            echo "SERVICE_NAME=calculadora-fertilidad-app-dev" >> $GITHUB_ENV
          fi

      # 🔒 Aprobación manual nativa de GitHub (recomendada)
      - name: Wait for manual approval (GitHub Environment)
        if: github.ref == 'refs/heads/main'
        run: echo "Waiting for manual approval in GitHub interface..."

      - name: Deploy to Cloud Run
        id: deploy
        continue-on-error: true
        run: |-
          gcloud run deploy $SERVICE_NAME \
            --source . \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --memory 512Mi \
            --timeout 600

      - name: Rollback if Deployment Fails
        if: failure()
        run: |
          echo "Deployment failed. Rolling back to previous revision..."
          gcloud run services update-traffic $SERVICE_NAME --to-latest --region us-central1
